# Generated by Django 3.1 on 2023-11-01 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='picture',
            field=models.ImageField(
                default='default.png', 
                upload_to='', 
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['png', 'jpg', 'jpeg'], 
                        message='Extensão não suportada'
                    )
                ], 
                verbose_name='User Picture'),
        ),
    ]
